# Generated by Django 3.2.11 on 2022-01-29 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supplier', '0001_initial'),
        ('p_item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StokM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe', models.CharField(choices=[('in', 'IN'), ('out', 'OUT')], max_length=20, null=True)),
                ('detail', models.TextField()),
                ('hargabeli', models.IntegerField(blank=True, default=0, null=True)),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='p_item.item_p')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplier.supplier')),
            ],
        ),
    ]
