# Generated by Django 3.2.11 on 2022-02-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_p',
            name='expired_date',
            field=models.DateField(null=True),
        ),
    ]
