# Generated by Django 3.2.11 on 2022-02-23 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_item', '0002_item_p_expired_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_p',
            name='expired_date',
        ),
    ]
