# Generated by Django 3.2.11 on 2022-02-02 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('p_item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.CharField(max_length=50, null=True)),
                ('totalharga', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('total_bayar', models.IntegerField()),
                ('total_pendapatan', models.IntegerField(blank=True, default=0, null=True)),
                ('cash', models.IntegerField()),
                ('kembalian', models.IntegerField()),
                ('note', models.TextField(blank=True, null=True)),
                ('tanggal', models.DateField(auto_now_add=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='KeranjangModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('discount', models.IntegerField(null=True)),
                ('totalharga', models.IntegerField()),
                ('total_untung', models.IntegerField(blank=True, default=0, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='p_item.item_p')),
            ],
        ),
    ]
