# Generated by Django 3.2.11 on 2022-04-20 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('k_akun', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jurnal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl', models.DateField(blank=True, null=True)),
                ('ket', models.TextField()),
                ('ref', models.CharField(blank=True, max_length=50, null=True)),
                ('nominal', models.IntegerField(blank=True, null=True)),
                ('tipe', models.CharField(choices=[('Debet', 'Debet'), ('Kredit', 'Kredit')], max_length=20)),
                ('akun', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='k_akun.akun')),
            ],
        ),
    ]
